enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-secret=HantaAkuYangTahu123
#dir="/mnt/c/Users/Regustia/Downloads/Compressed/"
continue=true

on-download-complete=${HOME}/.config/aria2/scripts/notif-windows.sh
