# Include other.conf
include other.conf

font_family      JetBrainsMono Nerd Font
font_size        10
italic_font      auto
bold_italic_font auto

cursor_trail 1

remember_window_size  yes

background_opacity 1
background_blur 1

# BEGIN_KITTY_THEME
# Atelier Estuary Dark
include current-theme.conf
# END_KITTY_THEME
